services:
  node-app:
    container_name: note-app
    ports:
      - 3000:3000
    depends_on:
      - mongo
    env_file:
      - .env

  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo_db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  

  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node-app

volumes:
  mongo_db: