name: first workflow


on:
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: ubunto-latest

    steps:
      - name: print a welcome message 
        run: echo"welcome to the first workflow" 

      - name: checkout repositry
        uses: actions/checkout@v4.2.2
        
      - name: list repositry files 
        run: ls -la 
